services:
    scylla-server-rust:
        environment:
            - PROD_SIREN_HOST_URL=siren:1883
            - PROD_SCYLLA=false

    client:
      extends:
        file: ./angular-client/compose.client.yml
        service: client
      build:
        context: ./angular-client
        args:
            BACKEND_URL: http://localhost:8000
