version: "3.8"

services:
  odyssey-timescale:
    container_name: odyssey-timescale
    image: timescale/timescaledb:2.13.1-pg15
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports: # needs to be published for charybdis, which runs outside of docker
      - 5432:5432
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data
    cpu_shares: 1024
    mem_limit: 3gb
    stop_grace_period: 1m

  client:
    container_name: client
    restart: unless-stopped
    image: ghcr.io/northeastern-electric-racing/argos:Develop-angular-client
    build:
      context: ./angular-client
      args:
        PROD: "true"
        BACKEND_URL: http://192.168.100.1:8000
        MAP_ACCESS_TOKEN: pk.eyJ1IjoibWNrZWVwIiwiYSI6ImNscXBrcmU1ZTBscWIya284cDFyYjR3Nm8ifQ.6TQHlxhAJzptZyV-W28dnw
      target: production
      dockerfile: Dockerfile
    ports:
      - 80:80
    cpu_shares: 512
    mem_limit: 1gb



volumes:
  db-data:
  


