version: "3.8"

services:
  odyssey-timescale:
    container_name: odyssey-timescale
    image: timescale/timescaledb:2.13.1-pg15
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports: # needs to be published for charybdis, which runs outside of docker
      - 5432:5432
    expose:
      - 5432

  scylla-server:
    container_name: scylla-server
    restart: unless-stopped
    image: ghcr.io/northeastern-electric-racing/argos:ghcr-action-scylla-server
    build:
      context: ./scylla-server
      target: production
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - odyssey-timescale
    environment:
      - SOURCE_DATABASE_URL=postgresql://postgres:password@odyssey-timescale:5432/timescaledb
      - PROD_SIREN_HOST_URL=host.docker.internal
      - PROD=true
    extra_hosts:
      - "host.docker.internal:host-gateway"

  client:
    container_name: client
    restart: unless-stopped
    image: ghcr.io/northeastern-electric-racing/argos:ghcr-action-angular-client
    build:
      context: ./angular-client
      args:
        PROD: true
        BACKEND_URL: http://192.168.100.1:8000
        MAP_ACCESS_TOKEN: pk.eyJ1IjoibWNrZWVwIiwiYSI6ImNscXBrcmU1ZTBscWIya284cDFyYjR3Nm8ifQ.6TQHlxhAJzptZyV-W28dnw
      target: production
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - scylla-server
  


