version: "3.8"

services:
  odyssey-timescale:
    container_name: odyssey-timescale
    image: timescale/timescaledb:2.13.1-pg15
    restart: unless-stopped
    network_mode: host
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    expose:
      - 5432
    tty: true

  scylla-server:
    container_name: scylla-server
    restart: unless-stopped
    image: ghcr.io/northeastern-electric-racing/argos:ghcr-action-scylla-server
    network_mode: host
    build:
      context: ./scylla-server
      target: production
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - odyssey-timescale

  client:
    container_name: client
    restart: unless-stopped
    image: ghcr.io/northeastern-electric-racing/argos:ghcr-action-angular-client
    network_mode: host
    build:
      context: ./angular-client
      target: production
      dockerfile: Dockerfile
    ports:
      - 4200:80
    depends_on:
      - scylla-server

