services:
  grafana:
    image: grafana/grafana:latest-ubuntu
    restart: unless-stopped
    environment:
      # increases the log level from info to debug
      #- GF_LOG_LEVEL=debug
      - GF_PLUGINS_PREINSTALL=grafana-zenoh-datasource@@https://github.com/Northeastern-Electric-Racing/zenoh-datasource/releases/download/v1.99.9/grafana-zenoh-datasource-1.99.9.zip
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-zenoh-datasource
    ports:
      - "${GRAFANA_HOST_PORT:-3000}:3000"
    volumes:
      - "grafana_storage:/var/lib/grafana"
