version: '3.8'

networks:
  shared_network:
    external: true  # Join the already created shared network

services:
  charybdis_app:
    build: .
    container_name: charybdis_app
    restart: unless-stopped
    environment:
      - LOCAL_DATABASE_URL=postgresql://postgres:password@odyssey-db:5432/postgres
    volumes:
      - .:/app
      - /app/node_modules  # Prevents overwriting local node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true  # Allows interactive shell
    networks:
      - shared_network  # Connect to shared network
