services:
    scylla-server:
        environment:
            - SCYLLA_ZENOH=true

    siren:
        extends:
            file: ../siren-base/compose.zenohd.yml
            service: siren

    calypso:
        extends:
            file: ../siren-base/compose.calypso.yml
            service: calypso
        depends_on:
            - siren
