services:
  scylla-server:
    depends_on:
      - siren
    environment:
      - SCYLLA_BATCH_UPSERT_TIME=20
      - SCYLLA_ZENOH=true
      - SCYLLA_ZENOH_CONF=/zenoh.json5
    volumes:
      - ../siren-base/zenoh.json5:/zenoh.json5:ro
    init: false

  client:
    extends:
      file: ../angular-client/compose.client.yml
      service: client

  grafana:
    extends:
      file: ../siren-base/compose.grafana.yml
      service: grafana
    depends_on:
      - siren

  # siren:
  #   extends:
  #     file: ../siren-base/compose.siren.yml
  #     service: siren

  siren-av:
    network_mode: host
    image: bluenviron/mediamtx:latest-ffmpeg
    volumes:
      - type: bind
        source: ../siren-base/mediamtx.yml
        target: /mediamtx.yml
        read_only: true
