version: "3.8"

services:
  odyssey-db:
    image: postgres:17.2
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=256MB"
    ports:
      - ${ODYSSEY_DB_PORT:-5432}:5432 # Exposed for external access if needed
    expose:
      - 5432 # Allow inter-container communication
    volumes:
      - db-data:/var/lib/postgresql/data
    cpu_shares: 1024
    stop_grace_period: 2m

  scylla-server:
    image: ghcr.io/northeastern-electric-racing/argos-scylla:develop
    build:
      context: ../scylla-server
    restart: unless-stopped
    ports:
      - ${SCYLLA_HOST_PORT:-8000}:${SCYLLA_HOST_PORT:-8000}
    depends_on:
      - odyssey-db
    environment:
      - DATABASE_URL=postgresql://postgres:password@odyssey-db:5432/postgres
      - RUST_LOG=warn,scylla_server=debug
      - SCYLLA_PORT=${SCYLLA_HOST_PORT:-8000}
      - SCYLLA_ZENOH_CONF=/zenoh.json5
    volumes:
      - ../siren-base/zenoh-scylla.json5:/zenoh.json5:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    cpu_shares: 1024
    stop_grace_period: 2m
    stop_signal: SIGINT
    init: true

volumes:
  db-data:
  grafana_storage:
