services:
  calypso:
    image: calypso:debug-efuses-v3
    command: ["calypso", "-e"]
    environment:
      - CALYPSO_SIREN_HOST_URL=localhost:1883
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
