export enum IdentifierDataType {
  DRIVER = 'Driver',
  LOCATION = 'location',
  SYSTEM = 'system',
  PACK_TEMP = 'Pack Temp',
  MOTOR_TEMP = 'Motor Temp',
  STATE_OF_CHARGE = 'Pack SOC',
  POINTS = 'Points',
  LATENCY = 'Latency',
  STEERING_ANGLE = 'Steering Angle',
  VOLTAGE = 'Voltage',
  VIEWERS = 'Viewers',
  SPEED = 'Speed',
  TORQUE = 'Torque',
  BRAKE_PRESSURE = 'Brake Pressure',
  CPU_USAGE = 'CPU Usage',
  CPU_TEMP = 'CPU Temp',
  RAM_USAGE = 'RAM Usage',
  WIFI_RSSI = 'WIFI RSSI',
  MCS = 'MCS',
  ACCELERATION = 'Acceleration'
}
