export enum IdentifierDataType {
  DRIVER = 'Driver',
  LOCATION = 'location',
  SYSTEM = 'system',
  PACK_TEMP = 'Pack Temp',
  MOTOR_TEMP = 'Motor Temp',
  MOTOR_USAGE = 'Motor Usage',
  COOL_USAGE = 'Cooling Usage',
  STATE_OF_CHARGE = 'Pack SOC',
  POINTS = 'Points',
  LATENCY = 'Latency',
  STEERING_ANGLE = 'Steering Angle',
  VOLTAGE = 'Voltage',
  VIEWERS = 'Viewers',
  SPEED = 'Speed',
  TORQUE = 'Torque',
  BRAKE_PRESSURE = 'Brake Pressure',
  CPUUsage = 'OnBoard-CpuUsage',
  CPUTemp = 'OnBoard-CpuTemp',
  RAMUsage = 'OnBoard-MemAvailable',
  WIFIRSSI = 'HaLow-RSSI',
  MCS = 'HaLow-ApMCS',
  ACCELERATION = 'Acceleration',
  CHARGE_CURRENT_LIMIT = 'Charge Current Limit',
  DISCHARGE_CURRENT_LIMIT = 'Discharge Current Limit',
  XYZAccel = 'XYZAcceleration'
}
