name: Build
on:
  push:
    branches:
      - main
      - develop
    paths:
      - "angular-client/**"
      - "scylla-server/**"
      - "compose/**"
      - ".github/workflows/build-check.yml"
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'
    paths:
      - "angular-client/**"
      - "scylla-server/**"
      - "compose/**"
      - ".github/workflows/build-check.yml"
jobs:
  run-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build Docker Compose
        working-directory: compose
        run: docker compose build
