name: Client CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "angular-client/**"
  pull_request:
    branches:
      - main
      - develop
      - "feature/**"
    paths:
      - "angular-client/**"

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20.17.0
          cache: "npm"
          cache-dependency-path: ./angular-client/package-lock.json
      - name: Install modules
        working-directory: ./angular-client
        run: npm ci
      - name: Run linting check
        working-directory: ./angular-client
        run: npm run lint --max-warnings=0
      - name: Run prettier check
        working-directory: ./angular-client
        run: npm run prettier-check
