name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
      - argos2
  paths:
    - 'flutter-client/**'
    - '.github/workflows/client-flutter-build.yml'

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./flutter-client
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
           channel: stable # or: beta, master (or main)

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Download Dependencies
        run: flutter pub get

      - name: Build
        run: flutter build web --base-href='/Argos/'

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: ./build/web/
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
