name: Scylla Rust CI

on:
   push:
      branches:
         - main
         - develop
      paths: ['scylla-server-rust/**', '.github/***']
   pull_request:
      branches:
         - main
         - develop
      paths: ['scylla-server-rust/**', '.github/**']


defaults:
    run:
        working-directory: scylla-server-rust


jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - name: Setup Rust
           uses: actions/checkout@v3
           with:
            submodules: recursive
         - name: Generate prisma
           run: cargo prisma generate
         - name: Build
           run: cargo build --verbose
         - name: Clippy
           run: cargo clippy --verbose -- -D warnings
